kind: Job
apiVersion: batch/v1
metadata:
  name: gdrive-bro-download-oneoff
spec:
    template:
      spec:
        volumes:
          - name: mldata
            nfs:
              server: 192.168.1.29
              path: /mnt/DroboFS/Shares/ml_data
        containers:
          - name: gdrive-download
            image: gclef/gdrive-download:1.2
            imagePullPolicy: "Always"
            volumeMounts:
              - name: mldata
                mountPath: /ml_data
            env:
              - name: OUTPUT_PATH
                value: /ml_data/OP_TC_data
        restartPolicy: Never
        imagePullSecrets:
          - name: registrycreds
    backoffLimit: 4