kind: Job
apiVersion: batch/v1
metadata:
  name: gdrive-bro-download-oneoff
spec:
    template:
      spec:
        volumes:
          - name: mldata
            nfs:
              server: 192.168.1.29
              path: /mnt/DroboFS/Shares/ml_data
          - name: gdrive-token-pickle
            secret:
              secretName: gdrive-token-pickle-secret
              items:
                - key: token.pickle
                  path: token.pickle
        containers:
          - name: gdrive-download
            image: gclef/gdrive-download:1.6
            imagePullPolicy: "Always"
            volumeMounts:
              - name: mldata
                mountPath: /ml_data
              - name: gdrive-token-pickle
                mountPath: "/app"
                readOnly: true
            env:
              - name: OUTPUT_PATH
                value: /ml_data/OP_TC_data
        restartPolicy: Never
        imagePullSecrets:
          - name: registrycreds
    backoffLimit: 4